apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: xapi-rate-service
  name: xapi-rate-service
  
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: xapi-rate-service
    deploymentconfig: xapi-rate-service
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: xapi-rate-service
        deploymentconfig: xapi-rate-service
    spec:
      containers:
      - name: xapi-rate-service
  
        env:
        - name: MESSAGE
          value: "hello world"
        - name: JAVA_OPTS
          value: ""
        - name: DB_STUDY
          valueFrom:
            secretKeyRef:
              name: xapi-secret
              key: db-study
        
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /app/config
          name: config
        - name: secret
          mountPath: /app/secret
          readOnly: true
      
        image: 172.30.1.1:5000/myproject/xapi-rate-service:latest   
        imagePullPolicy: Always          
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
        - containerPort: 8888
        
        command: ["/bin/sh", "-c"]
        args: ["cd /app; java $JAVA_OPTS -jar xapi-rate-service.jar --spring.profiles.active=dev"]       
               
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      
      volumes:
      - name: data
        emptyDir: {}
        
      - name: config
        configMap:
          name: rate-service-config
          items:
          - key: rate-service-config.yml
            path: application.yml
            
      - name: secret
        secret:
          secretName: xapi-secret
          items:
          - key: db-study
            path: db-study
          
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - xapi-rate-service
        from:
          kind: ImageStreamTag
          name: 'xapi-rate-service:latest'
          namespace: myproject       
      type: ImageChange