apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: xapi-ret-service
  name: xapi-ret-service
  
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: xapi-ret-service
    deploymentconfig: xapi-ret-service
  stretgy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: xapi-ret-service
        deploymentconfig: xapi-ret-service
    spec:
      containers:
      - name: xapi-ret-service
  
        env:
        - name: JAVA_OPTS
          value: ""
        
        volumeMounts:
        - mountPath: /data
          name: data
      
        image: 172.30.1.1:5000/myproject/xapi-ret-service:latest   
        imagePullPolicy: Always          
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
        - containerPort: 8888
        
        command: ["/bin/sh", "-c"]
        args: ["cd /app; java $JAVA_OPTS -jar xapi-ret-service.jar --spring.profiles.active=dev"]       
               
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      
      volumes:
      - name: data
        emptyDir: {}
          
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - xapi-ret-service
        from:
          kind: ImageStreamTag
          name: 'xapi-ret-service:latest'
          namespace: myproject       
      type: ImageChange