apiVersion: v1
kind: Pod
metadata:
  name: xapi-rate-service
  labels:
    app: xapi-rate-service
    deployment: xapi-rate-service
    deploymentconfig: xapi-rate-service
spec:
  containers:
  - name: xapi-rate-service
  
    env:
    - name: MESSAGE
      value: "hello world"
    - name: JAVA_OPTS
      value: ""
    - name: DB_STUDY
      valueFrom:
        secretKeyRef:
          name: xapi-secret
          key: db-study
    
    volumeMounts:
    - mountPath: /data
      name: data
    - mountPath: /app/config
      name: config
    - name: secret
      mountPath: /app/secret
      readOnly: true
    image: 172.30.1.1:5000/myproject/xapi-rate-service:latest   
    ports:
    - containerPort: 8888
    
    #command: ["sh", "-c", "java $JAVA_OPTS -jar xapi-rate-service.jar"]
    command: ["/bin/sh", "-c"]
    #args: ["/bin/echo \"${MESSAGE}\"; cd /app; ls"]
    args: ["cd /app; java $JAVA_OPTS -jar xapi-rate-service.jar --spring.profiles.active=dev"]
    
  volumes:
    - name: data
      emptyDir: {}
      
    - name: config
      configMap:
        name: rate-service-config
        items:
        - key: rate-service-config.yml
          path: application.yml
          
    - name: secret
      secret:
        secretName: xapi-secret
        items:
        - key: db-study
          path: db-study   